
Showing logs for build [32mvicky-socs-test-python-jenkinsx-82x5p-4[0m stage [32mfrom-build-pack[0m and container [32mstep-credential-initializer-jwd2t[0m
{"level":"warn","ts":1584536444.5596023,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1584536444.5599391,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mvicky-socs-test-python-jenkinsx-82x5p-4[0m stage [32mfrom-build-pack[0m and container [32mstep-working-dir-initializer-9x9hc[0m
{"level":"warn","ts":1584536445.114306,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1584536445.1157012,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mvicky-socs-test-python-jenkinsx-82x5p-4[0m stage [32mfrom-build-pack[0m and container [32mstep-place-tools[0m

Showing logs for build [32mvicky-socs-test-python-jenkinsx-82x5p-4[0m stage [32mfrom-build-pack[0m and container [32mstep-git-source-vicky-socs-test-python-jenkinsx-82x5p-f795p[0m
{"level":"warn","ts":1584536451.282656,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1584536453.951457,"logger":"fallback-logger","caller":"git/git.go:103","msg":"Successfully cloned https://github.com/vicky-socs/test-python-jenkinsx.git @ v0.0.10 in path /workspace/source"}

Showing logs for build [32mvicky-socs-test-python-jenkinsx-82x5p-4[0m stage [32mfrom-build-pack[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=staging:40038a3d368178b6cef0b3a7c495a6066778ce9b
WARNING: no SHAs to merge, falling back to initial cloned commit

Showing logs for build [32mvicky-socs-test-python-jenkinsx-82x5p-4[0m stage [32mfrom-build-pack[0m and container [32mstep-setup-jx-git-credentials[0m
Generated Git credentials file /workspace/xdg_config/git/credentials

Showing logs for build [32mvicky-socs-test-python-jenkinsx-82x5p-4[0m stage [32mfrom-build-pack[0m and container [32mstep-build-python-unittest[0m

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

Showing logs for build [32mvicky-socs-test-python-jenkinsx-82x5p-4[0m stage [32mfrom-build-pack[0m and container [32mstep-build-container-build[0m
[36mINFO[0m[0000] Downloading base image python:onbuild        
2020/03/18 13:00:56 No matching credentials were found, falling back on anonymous
[36mINFO[0m[0002] Error while retrieving image from cache: getting file info: stat /workspace/sha256:43780a8431c53f4afd734ad795e03127c0c607337a60639c5903a51a03535c22: no such file or directory 
[36mINFO[0m[0002] Downloading base image python:onbuild        
2020/03/18 13:00:59 No matching credentials were found, falling back on anonymous
[36mINFO[0m[0003] Executing 3 build triggers                   
[36mINFO[0m[0003] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0003] Checking for cached layer 685249416972.dkr.ecr.ap-south-1.amazonaws.com/todo/cache:20ed5631d983ab35ddcc4224cde40d34ba4dcc68c4ee26635bbf30d01c3c2af6... 
[36mINFO[0m[0004] Using caching version of cmd: RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0004] Using files from context: [/workspace/source] 
[36mINFO[0m[0004] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0004] cmd: EXPOSE                                  
[36mINFO[0m[0004] Adding exposed port: 8080/tcp                
[36mINFO[0m[0004] Skipping unpacking as no commands require it. 
[36mINFO[0m[0004] Taking snapshot of full filesystem...        
[36mINFO[0m[0004] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0004] COPY requirements.txt /usr/src/app/          
[36mINFO[0m[0004] Taking snapshot of files...                  
[36mINFO[0m[0004] RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0004] Found cached layer, extracting to filesystem 
[36mINFO[0m[0005] Taking snapshot of files...                  
[36mINFO[0m[0005] Using files from context: [/workspace/source] 
[36mINFO[0m[0005] COPY . /usr/src/app                          
[36mINFO[0m[0005] Taking snapshot of files...                  
[36mINFO[0m[0005] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0005] COPY requirements.txt .                      
[36mINFO[0m[0005] Taking snapshot of files...                  
[36mINFO[0m[0005] ENV PORT 8080                                
[36mINFO[0m[0005] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0005] EXPOSE 8080                                  
[36mINFO[0m[0005] cmd: EXPOSE                                  
[36mINFO[0m[0005] Adding exposed port: 8080/tcp                
[36mINFO[0m[0005] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0005] ENTRYPOINT ["python"]                        
[36mINFO[0m[0005] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0005] CMD ["app.py"]                               
[36mINFO[0m[0005] No files changed in this command, skipping snapshotting. 
2020/03/18 13:01:02 existing blob: sha256:490280dbcfb772eb5731f059e38fcfacaeb75b4d005af7c249fd51926db2bd62
2020/03/18 13:01:02 existing blob: sha256:1c7fe136a31e13a1c879245672184ced3b9fc590989ba42a522a57b071a9c1aa
2020/03/18 13:01:02 existing blob: sha256:ece825d3308bbf98f708d95475ccd880497a1e2979ff4ef2534d49049a18488f
2020/03/18 13:01:02 existing blob: sha256:06854774e2f35e4763103a446112c67322913a6177bea69eb49663e0166e6d6d
2020/03/18 13:01:02 existing blob: sha256:e10b68fb77e6e91453cd4c1b02e2d77aa23a857cd8eb250617129d074478e1a5
2020/03/18 13:01:02 existing blob: sha256:f0db43b9b8da254cebc77bf871006df01219e195b9853616b9f708f124a00f3a
2020/03/18 13:01:02 existing blob: sha256:e96bc319bce0351d1157092352bc5f85f8800c745388e60e86d06dec99285b45
2020/03/18 13:01:02 existing blob: sha256:2d21c767035c4593de8bf7ad9781aa83ba110871d1a50871192f4e3480e6f11d
2020/03/18 13:01:02 existing blob: sha256:e2c0fb34dff3a1d32346b92e53fb88a14d1987b402a2348cb379c039687fabe2
2020/03/18 13:01:02 pushed blob: sha256:08efb4ac00327fab63a5232cc16732ebe7407c7e469d2d095e25dc0a002e4061
2020/03/18 13:01:03 pushed blob: sha256:6da60e23f9ba8e35cd8c3940ab2f89c0320be04113e50488a8046cf974b09830
2020/03/18 13:01:03 pushed blob: sha256:7fd43febcfe97af61ef5997f1bffd8d641942aeabcaa381cd1c4f0facde59e2f
2020/03/18 13:01:04 pushed blob: sha256:7adedad095eabd427c2347a88c41ad3422fea0f695d91ee593e583a6fccbdd6d
2020/03/18 13:01:05 pushed blob: sha256:f2e1e069c94833819abecb795c812d853d3929e20c3f81b46f5d4383c85db7d1
2020/03/18 13:01:05 685249416972.dkr.ecr.ap-south-1.amazonaws.com/vicky-socs/test-python-jenkinsx:0.0.10: digest: sha256:6c03e9fe99839b7932b0723566d3186d284f9c935f3ccbccd810d357e426d0a2 size: 2385

Showing logs for build [32mvicky-socs-test-python-jenkinsx-82x5p-4[0m stage [32mfrom-build-pack[0m and container [32mstep-build-post-build[0m
no CVE provider running in the current ** namespace so skip adding image to be analysed

Showing logs for build [32mvicky-socs-test-python-jenkinsx-82x5p-4[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-changelog[0m
Converted /workspace/source/charts/test-python-jenkinsx to an unshallow repository
Generating change log from git ref 0bb7c7e73153b09cf26d938a3a17b9695afe7065 => d28d53702e1862842f211b59b9a6a203c5b1a251
Associating user x-0 in users.jenkins.io with email jenkins-x@googlegroups.com to git GitProvider user with login -0 as emails match
Adding label jenkins.io/git-github-userid=-0 to user x-0 in users.jenkins.io
WARNING: Failed to enrich commit 9f713b4ec1faa51e9c761f1af747b4d954b27d0a with issues: User.jenkins.io "x-0" is invalid: metadata.labels: Invalid value: "-0": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
Associating user x-0 in users.jenkins.io with email jenkins-x@googlegroups.com to git GitProvider user with login -0 as emails match
Adding label jenkins.io/git-github-userid=-0 to user x-0 in users.jenkins.io
WARNING: Failed to enrich commit 9f713b4ec1faa51e9c761f1af747b4d954b27d0a with issues: User.jenkins.io "x-0" is invalid: metadata.labels: Invalid value: "-0": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
Finding issues in commit messages using git format
WARNING: No release found for vicky-socs/test-python-jenkinsx and tag v0.0.10 so creating a new release
Updated the release information at https://github.com/vicky-socs/test-python-jenkinsx/releases/tag/v0.0.10
generated: /workspace/source/charts/test-python-jenkinsx/templates/release.yaml
Created Release test-python-jenkinsx-0-0-10 resource in namespace **
Updating PipelineActivity vicky-socs-test-python-jenkinsx-staging-4 with version 0.0.10
Updated PipelineActivities vicky-socs-test-python-jenkinsx-staging-4 with release notes URL: https://github.com/vicky-socs/test-python-jenkinsx/releases/tag/v0.0.10

Showing logs for build [32mvicky-socs-test-python-jenkinsx-82x5p-4[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-helm-release[0m
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Adding missing Helm repo: storage.googleapis.com https://storage.googleapis.com/chartmuseum.jenkins-x.io
Successfully added Helm repository storage.googleapis.com.
Adding missing Helm repo: jenkins-x-chartmuseum http://jenkins-x-chartmuseum:8080
Successfully added Helm repository jenkins-x-chartmuseum.
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Uploading chart file test-python-jenkinsx-0.0.10.tgz to http://jenkins-x-chartmuseum:8080/api/charts
Received 201 response: {"saved":true}

Showing logs for build [32mvicky-socs-test-python-jenkinsx-82x5p-4[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-jx-promote[0m
WARNING: prow based install so skip waiting for the merge of Pull Requests to go green as currently there is an issue with gettingstatuses from the PR, see https://github.com/jenkins-x/**/issues/2410
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Promoting app test-python-jenkinsx version 0.0.10 to namespace **-production
WARNING: 
WARNING: Waiting for the fork of ********/environment-non-prod-cluster-production to appear...
Forked Git repository to https://github.com/********/environment-non-prod-cluster-production
Created Pull Request: https://github.com/vicky-socs/environment-non-prod-cluster-production/pull/1
Added label updatebot to Pull Request https://github.com/vicky-socs/environment-non-prod-cluster-production/pull/1
got git provider status pending from PR https://github.com/vicky-socs/environment-non-prod-cluster-production/pull/1
got git provider status pending from PR https://github.com/vicky-socs/environment-non-prod-cluster-production/pull/1
got git provider status pending from PR https://github.com/vicky-socs/environment-non-prod-cluster-production/pull/1
got git provider status pending from PR https://github.com/vicky-socs/environment-non-prod-cluster-production/pull/1
Pull Request https://github.com/vicky-socs/environment-non-prod-cluster-production/pull/1 is merged at sha b40e6b96c7e33f1f0467c02d8dd8961615d43b56
Pull Request merged but we are not waiting for the update pipeline to complete!
WARNING: Could not find the service URL in namespace **-production for names test-python-jenkinsx, **-test-python-jenkinsx, **-production-test-python-jenkinsx
Promoting app test-python-jenkinsx version 0.0.10 to namespace **-staging
WARNING: 
Created Pull Request: https://github.com/vicky-socs/environment-non-prod-cluster-staging/pull/10
Added label updatebot to Pull Request https://github.com/vicky-socs/environment-non-prod-cluster-staging/pull/10
got git provider status pending from PR https://github.com/vicky-socs/environment-non-prod-cluster-staging/pull/10
got git provider status pending from PR https://github.com/vicky-socs/environment-non-prod-cluster-staging/pull/10
got git provider status pending from PR https://github.com/vicky-socs/environment-non-prod-cluster-staging/pull/10
got git provider status pending from PR https://github.com/vicky-socs/environment-non-prod-cluster-staging/pull/10
Pull Request https://github.com/vicky-socs/environment-non-prod-cluster-staging/pull/10 is merged at sha 91498eb7fe2a01bd6a12841217e9b4135ebbd423
Pull Request merged but we are not waiting for the update pipeline to complete!
