
Showing logs for build [32mvicky-socs-test-python-jenkinsx-vnvkz-5[0m stage [32mfrom-build-pack[0m and container [32mstep-credential-initializer-9sm4j[0m
{"level":"warn","ts":1584538425.7001362,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1584538425.7004435,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mvicky-socs-test-python-jenkinsx-vnvkz-5[0m stage [32mfrom-build-pack[0m and container [32mstep-working-dir-initializer-f6pmp[0m
{"level":"warn","ts":1584538426.336253,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1584538426.3408184,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mvicky-socs-test-python-jenkinsx-vnvkz-5[0m stage [32mfrom-build-pack[0m and container [32mstep-place-tools[0m

Showing logs for build [32mvicky-socs-test-python-jenkinsx-vnvkz-5[0m stage [32mfrom-build-pack[0m and container [32mstep-git-source-vicky-socs-test-python-jenkinsx-vnvkz-cmn7x[0m
{"level":"warn","ts":1584538432.6048315,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1584538435.1254408,"logger":"fallback-logger","caller":"git/git.go:103","msg":"Successfully cloned https://github.com/vicky-socs/test-python-jenkinsx.git @ v0.0.11 in path /workspace/source"}

Showing logs for build [32mvicky-socs-test-python-jenkinsx-vnvkz-5[0m stage [32mfrom-build-pack[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=staging:3834897282e2d619ec556f6ca3a97a5d637cd1cb
WARNING: no SHAs to merge, falling back to initial cloned commit

Showing logs for build [32mvicky-socs-test-python-jenkinsx-vnvkz-5[0m stage [32mfrom-build-pack[0m and container [32mstep-setup-jx-git-credentials[0m
Generated Git credentials file /workspace/xdg_config/git/credentials

Showing logs for build [32mvicky-socs-test-python-jenkinsx-vnvkz-5[0m stage [32mfrom-build-pack[0m and container [32mstep-build-python-unittest[0m

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

Showing logs for build [32mvicky-socs-test-python-jenkinsx-vnvkz-5[0m stage [32mfrom-build-pack[0m and container [32mstep-build-container-build[0m
[36mINFO[0m[0000] Downloading base image python:onbuild        
2020/03/18 13:33:59 No matching credentials were found, falling back on anonymous
[36mINFO[0m[0002] Error while retrieving image from cache: getting file info: stat /workspace/sha256:43780a8431c53f4afd734ad795e03127c0c607337a60639c5903a51a03535c22: no such file or directory 
[36mINFO[0m[0002] Downloading base image python:onbuild        
2020/03/18 13:34:01 No matching credentials were found, falling back on anonymous
[36mINFO[0m[0004] Executing 3 build triggers                   
[36mINFO[0m[0004] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0004] Checking for cached layer 685249416972.dkr.ecr.ap-south-1.amazonaws.com/todo/cache:20ed5631d983ab35ddcc4224cde40d34ba4dcc68c4ee26635bbf30d01c3c2af6... 
[36mINFO[0m[0005] Using caching version of cmd: RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0005] Using files from context: [/workspace/source] 
[36mINFO[0m[0005] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0005] cmd: EXPOSE                                  
[36mINFO[0m[0005] Adding exposed port: 8080/tcp                
[36mINFO[0m[0005] Skipping unpacking as no commands require it. 
[36mINFO[0m[0005] Taking snapshot of full filesystem...        
[36mINFO[0m[0005] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0005] COPY requirements.txt /usr/src/app/          
[36mINFO[0m[0005] Taking snapshot of files...                  
[36mINFO[0m[0005] RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0005] Found cached layer, extracting to filesystem 
[36mINFO[0m[0005] Taking snapshot of files...                  
[36mINFO[0m[0005] Using files from context: [/workspace/source] 
[36mINFO[0m[0005] COPY . /usr/src/app                          
[36mINFO[0m[0005] Taking snapshot of files...                  
[36mINFO[0m[0005] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0005] COPY requirements.txt .                      
[36mINFO[0m[0005] Taking snapshot of files...                  
[36mINFO[0m[0005] ENV PORT 8080                                
[36mINFO[0m[0005] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0005] EXPOSE 8080                                  
[36mINFO[0m[0005] cmd: EXPOSE                                  
[36mINFO[0m[0005] Adding exposed port: 8080/tcp                
[36mINFO[0m[0005] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0005] ENTRYPOINT ["python"]                        
[36mINFO[0m[0005] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0005] CMD ["app.py"]                               
[36mINFO[0m[0005] No files changed in this command, skipping snapshotting. 
2020/03/18 13:34:05 existing blob: sha256:e2c0fb34dff3a1d32346b92e53fb88a14d1987b402a2348cb379c039687fabe2
2020/03/18 13:34:05 existing blob: sha256:f0db43b9b8da254cebc77bf871006df01219e195b9853616b9f708f124a00f3a
2020/03/18 13:34:05 existing blob: sha256:1c7fe136a31e13a1c879245672184ced3b9fc590989ba42a522a57b071a9c1aa
2020/03/18 13:34:05 existing blob: sha256:06854774e2f35e4763103a446112c67322913a6177bea69eb49663e0166e6d6d
2020/03/18 13:34:05 existing blob: sha256:ece825d3308bbf98f708d95475ccd880497a1e2979ff4ef2534d49049a18488f
2020/03/18 13:34:05 existing blob: sha256:2d21c767035c4593de8bf7ad9781aa83ba110871d1a50871192f4e3480e6f11d
2020/03/18 13:34:05 existing blob: sha256:e10b68fb77e6e91453cd4c1b02e2d77aa23a857cd8eb250617129d074478e1a5
2020/03/18 13:34:05 existing blob: sha256:490280dbcfb772eb5731f059e38fcfacaeb75b4d005af7c249fd51926db2bd62
2020/03/18 13:34:05 existing blob: sha256:e96bc319bce0351d1157092352bc5f85f8800c745388e60e86d06dec99285b45
2020/03/18 13:34:05 pushed blob: sha256:7249ff47c7887a0abcca48ff232ea690f5659576aab16194f649ce0706c8711a
2020/03/18 13:34:05 pushed blob: sha256:b6bb0435194da62e83fa25f003c02872e33e42dc03539525aa88a489823516d1
2020/03/18 13:34:06 pushed blob: sha256:1dd76c2ecb6c26176685d57395f7c4afa9e8e5529af6228b87ab718029d3a393
2020/03/18 13:34:06 pushed blob: sha256:cd750ae3c269ce45c4149f0c54836ddf50fa9151b00d4d2069e58d3c2c130116
2020/03/18 13:34:07 pushed blob: sha256:a35f0c0a04152adf775f41ba2c8a7f653c9b9c8595bfbf68761d311f0694b047
2020/03/18 13:34:07 685249416972.dkr.ecr.ap-south-1.amazonaws.com/vicky-socs/test-python-jenkinsx:0.0.11: digest: sha256:a26cd0eb3e1f23f67ceecb67e6f58fd105cb134df7b1c855da0b08eb392df67f size: 2385

Showing logs for build [32mvicky-socs-test-python-jenkinsx-vnvkz-5[0m stage [32mfrom-build-pack[0m and container [32mstep-build-post-build[0m
no CVE provider running in the current ** namespace so skip adding image to be analysed

Showing logs for build [32mvicky-socs-test-python-jenkinsx-vnvkz-5[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-changelog[0m
Converted /workspace/source/charts/test-python-jenkinsx to an unshallow repository
Generating change log from git ref d28d53702e1862842f211b59b9a6a203c5b1a251 => 7bc89072fa43af1448bc1884c390c43972d6d024
Associating user x-0 in users.jenkins.io with email jenkins-x@googlegroups.com to git GitProvider user with login -0 as emails match
Adding label jenkins.io/git-github-userid=-0 to user x-0 in users.jenkins.io
WARNING: Failed to enrich commit 747a520e3eb9a9f989fc26499ef483cc4b2188e7 with issues: User.jenkins.io "x-0" is invalid: metadata.labels: Invalid value: "-0": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
Associating user x-0 in users.jenkins.io with email jenkins-x@googlegroups.com to git GitProvider user with login -0 as emails match
Adding label jenkins.io/git-github-userid=-0 to user x-0 in users.jenkins.io
WARNING: Failed to enrich commit 747a520e3eb9a9f989fc26499ef483cc4b2188e7 with issues: User.jenkins.io "x-0" is invalid: metadata.labels: Invalid value: "-0": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
Finding issues in commit messages using git format
Associating user x-0 in users.jenkins.io with email jenkins-x@googlegroups.com to git GitProvider user with login -0 as emails match
Adding label jenkins.io/git-github-userid=-0 to user x-0 in users.jenkins.io
WARNING: Failed to enrich commit 2566ffdd8325f8569488bf84a0943051bc0355df with issues: User.jenkins.io "x-0" is invalid: metadata.labels: Invalid value: "-0": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
Associating user x-0 in users.jenkins.io with email jenkins-x@googlegroups.com to git GitProvider user with login -0 as emails match
Adding label jenkins.io/git-github-userid=-0 to user x-0 in users.jenkins.io
WARNING: Failed to enrich commit 2566ffdd8325f8569488bf84a0943051bc0355df with issues: User.jenkins.io "x-0" is invalid: metadata.labels: Invalid value: "-0": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
WARNING: No release found for vicky-socs/test-python-jenkinsx and tag v0.0.11 so creating a new release
Updated the release information at https://github.com/vicky-socs/test-python-jenkinsx/releases/tag/v0.0.11
generated: /workspace/source/charts/test-python-jenkinsx/templates/release.yaml
Created Release test-python-jenkinsx-0-0-11 resource in namespace **
Updating PipelineActivity vicky-socs-test-python-jenkinsx-staging-5 with version 0.0.11
Updated PipelineActivities vicky-socs-test-python-jenkinsx-staging-5 with release notes URL: https://github.com/vicky-socs/test-python-jenkinsx/releases/tag/v0.0.11

Showing logs for build [32mvicky-socs-test-python-jenkinsx-vnvkz-5[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-helm-release[0m
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Adding missing Helm repo: storage.googleapis.com https://storage.googleapis.com/chartmuseum.jenkins-x.io
Successfully added Helm repository storage.googleapis.com.
Adding missing Helm repo: jenkins-x-chartmuseum http://jenkins-x-chartmuseum:8080
Successfully added Helm repository jenkins-x-chartmuseum.
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Uploading chart file test-python-jenkinsx-0.0.11.tgz to http://jenkins-x-chartmuseum:8080/api/charts
Received 201 response: {"saved":true}

Showing logs for build [32mvicky-socs-test-python-jenkinsx-vnvkz-5[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-jx-promote[0m
WARNING: prow based install so skip waiting for the merge of Pull Requests to go green as currently there is an issue with gettingstatuses from the PR, see https://github.com/jenkins-x/**/issues/2410
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Promoting app test-python-jenkinsx version 0.0.11 to namespace **-production
WARNING: 
Created Pull Request: https://github.com/vicky-socs/environment-non-prod-cluster-production/pull/2
Added label updatebot to Pull Request https://github.com/vicky-socs/environment-non-prod-cluster-production/pull/2
got git provider status pending from PR https://github.com/vicky-socs/environment-non-prod-cluster-production/pull/2
got git provider status pending from PR https://github.com/vicky-socs/environment-non-prod-cluster-production/pull/2
got git provider status pending from PR https://github.com/vicky-socs/environment-non-prod-cluster-production/pull/2
got git provider status pending from PR https://github.com/vicky-socs/environment-non-prod-cluster-production/pull/2
Pull Request https://github.com/vicky-socs/environment-non-prod-cluster-production/pull/2 is merged at sha 2a084f56f6aaf7fe77cd65ffd57380708be7caba
Pull Request merged but we are not waiting for the update pipeline to complete!
Promoting app test-python-jenkinsx version 0.0.11 to namespace **-staging
WARNING: 
Created Pull Request: https://github.com/vicky-socs/environment-non-prod-cluster-staging/pull/11
Added label updatebot to Pull Request https://github.com/vicky-socs/environment-non-prod-cluster-staging/pull/11
got git provider status pending from PR https://github.com/vicky-socs/environment-non-prod-cluster-staging/pull/11
got git provider status pending from PR https://github.com/vicky-socs/environment-non-prod-cluster-staging/pull/11
got git provider status pending from PR https://github.com/vicky-socs/environment-non-prod-cluster-staging/pull/11
got git provider status pending from PR https://github.com/vicky-socs/environment-non-prod-cluster-staging/pull/11
got git provider status pending from PR https://github.com/vicky-socs/environment-non-prod-cluster-staging/pull/11
Pull Request https://github.com/vicky-socs/environment-non-prod-cluster-staging/pull/11 is merged at sha 6140346a867baa0e707bb645a2ece6635ecb4bd6
Pull Request merged but we are not waiting for the update pipeline to complete!
