
Showing logs for build [32mvicky-socs-test-python-jenkinsx-f5llb-1[0m stage [32mfrom-build-pack[0m and container [32mstep-credential-initializer-vjcvp[0m
{"level":"warn","ts":1584536095.671586,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1584536095.6718953,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mvicky-socs-test-python-jenkinsx-f5llb-1[0m stage [32mfrom-build-pack[0m and container [32mstep-working-dir-initializer-jbxbg[0m
{"level":"warn","ts":1584536096.1964679,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1584536096.1975374,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mvicky-socs-test-python-jenkinsx-f5llb-1[0m stage [32mfrom-build-pack[0m and container [32mstep-place-tools[0m

Showing logs for build [32mvicky-socs-test-python-jenkinsx-f5llb-1[0m stage [32mfrom-build-pack[0m and container [32mstep-git-source-vicky-socs-test-python-jenkinsx-f5llb-xl7md[0m
{"level":"warn","ts":1584536102.4157357,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1584536106.3441007,"logger":"fallback-logger","caller":"git/git.go:103","msg":"Successfully cloned https://github.com/vicky-socs/test-python-jenkinsx.git @ master in path /workspace/source"}

Showing logs for build [32mvicky-socs-test-python-jenkinsx-f5llb-1[0m stage [32mfrom-build-pack[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=master:a6d2819530ccb8bf8cdb9970f7e081a6b5900274,3:903df94cf9c19c56402b31238ef870fbd232ca11
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git fetch origin --unshallow 903df94cf9c19c56402b31238ef870fbd232ca11: a6d2819530ccb8bf8cdb9970f7e081a6b5900274:
DEBUG: ran git fetch --unshallow origin 903df94cf9c19c56402b31238ef870fbd232ca11: a6d2819530ccb8bf8cdb9970f7e081a6b5900274: in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git branch
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git checkout master
DEBUG: ran git checkout master in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git reset --hard a6d2819530ccb8bf8cdb9970f7e081a6b5900274
DEBUG: ran git reset --hard a6d2819530ccb8bf8cdb9970f7e081a6b5900274 in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git clean -fd .
DEBUG: ran clean --force -d . in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git merge 903df94cf9c19c56402b31238ef870fbd232ca11
DEBUG: ran git merge 903df94cf9c19c56402b31238ef870fbd232ca11 in 
DEBUG: JX_LOG_LEVEL=error LC_ALL=C git log --format=%H%x1f%an%x1f%ae%x1f%cn%x1f%ce%x1f%s%n%b%x1e a6d2819530ccb8bf8cdb9970f7e081a6b5900274..HEAD
Merged SHA 903df94cf9c19c56402b31238ef870fbd232ca11 with commit message 'Merge branch 'staging' of github.com:vicky-socs/test-python-jenkinsx into staging' into base branch master
Merged SHA 99d0002e08fec6cc9256f8d3236caba5b4348404 with commit message 'test3 reverify' into base branch master
Merged SHA fb592cbac6ae56aa5b0ff272a50ff662862269e2 with commit message 'Merge pull request #2 from vicky-socs/feature' into base branch master
Merged SHA 0622a72dc3dad212e9b15aef541b6f850e2ce1e0 with commit message 'test' into base branch master
Merged SHA 743a897af5708499983a63ecfa000ad9e4fb6ca1 with commit message 'test 2' into base branch master
Merged SHA a6a65db7d4a9ccbfcfa7b0ddd94d461ce44f19ae with commit message 'test 2' into base branch master

Showing logs for build [32mvicky-socs-test-python-jenkinsx-f5llb-1[0m stage [32mfrom-build-pack[0m and container [32mstep-build-python-unittest[0m

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

Showing logs for build [32mvicky-socs-test-python-jenkinsx-f5llb-1[0m stage [32mfrom-build-pack[0m and container [32mstep-build-container-build[0m
[36mINFO[0m[0000] Downloading base image python:onbuild        
2020/03/18 12:55:10 No matching credentials were found, falling back on anonymous
[36mINFO[0m[0002] Error while retrieving image from cache: getting file info: stat /workspace/sha256:43780a8431c53f4afd734ad795e03127c0c607337a60639c5903a51a03535c22: no such file or directory 
[36mINFO[0m[0002] Downloading base image python:onbuild        
2020/03/18 12:55:12 No matching credentials were found, falling back on anonymous
[36mINFO[0m[0003] Executing 3 build triggers                   
[36mINFO[0m[0003] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0003] Checking for cached layer 685249416972.dkr.ecr.ap-south-1.amazonaws.com/todo/cache:20ed5631d983ab35ddcc4224cde40d34ba4dcc68c4ee26635bbf30d01c3c2af6... 
[36mINFO[0m[0004] Using caching version of cmd: RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0004] Using files from context: [/workspace/source] 
[36mINFO[0m[0004] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0004] cmd: EXPOSE                                  
[36mINFO[0m[0004] Adding exposed port: 8080/tcp                
[36mINFO[0m[0004] Skipping unpacking as no commands require it. 
[36mINFO[0m[0004] Taking snapshot of full filesystem...        
[36mINFO[0m[0004] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0004] COPY requirements.txt /usr/src/app/          
[36mINFO[0m[0004] Taking snapshot of files...                  
[36mINFO[0m[0004] RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0004] Found cached layer, extracting to filesystem 
[36mINFO[0m[0004] Taking snapshot of files...                  
[36mINFO[0m[0004] Using files from context: [/workspace/source] 
[36mINFO[0m[0004] COPY . /usr/src/app                          
[36mINFO[0m[0004] Taking snapshot of files...                  
[36mINFO[0m[0004] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0004] COPY requirements.txt .                      
[36mINFO[0m[0004] Taking snapshot of files...                  
[36mINFO[0m[0004] ENV PORT 8080                                
[36mINFO[0m[0004] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0004] EXPOSE 8080                                  
[36mINFO[0m[0004] cmd: EXPOSE                                  
[36mINFO[0m[0004] Adding exposed port: 8080/tcp                
[36mINFO[0m[0004] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0004] ENTRYPOINT ["python"]                        
[36mINFO[0m[0004] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0004] CMD ["app.py"]                               
[36mINFO[0m[0004] No files changed in this command, skipping snapshotting. 
2020/03/18 12:55:15 existing blob: sha256:490280dbcfb772eb5731f059e38fcfacaeb75b4d005af7c249fd51926db2bd62
2020/03/18 12:55:15 existing blob: sha256:06854774e2f35e4763103a446112c67322913a6177bea69eb49663e0166e6d6d
2020/03/18 12:55:15 existing blob: sha256:1c7fe136a31e13a1c879245672184ced3b9fc590989ba42a522a57b071a9c1aa
2020/03/18 12:55:15 existing blob: sha256:ece825d3308bbf98f708d95475ccd880497a1e2979ff4ef2534d49049a18488f
2020/03/18 12:55:15 existing blob: sha256:e10b68fb77e6e91453cd4c1b02e2d77aa23a857cd8eb250617129d074478e1a5
2020/03/18 12:55:15 existing blob: sha256:2d21c767035c4593de8bf7ad9781aa83ba110871d1a50871192f4e3480e6f11d
2020/03/18 12:55:15 existing blob: sha256:f0db43b9b8da254cebc77bf871006df01219e195b9853616b9f708f124a00f3a
2020/03/18 12:55:15 existing blob: sha256:e96bc319bce0351d1157092352bc5f85f8800c745388e60e86d06dec99285b45
2020/03/18 12:55:15 existing blob: sha256:e2c0fb34dff3a1d32346b92e53fb88a14d1987b402a2348cb379c039687fabe2
2020/03/18 12:55:15 pushed blob: sha256:bdcf2e35502e97a7356b368d5837abf66ab3723e9be609a1c5613f7ece4999ce
2020/03/18 12:55:15 pushed blob: sha256:e671ad56cd4d80047510bbe360f65ffbfcd0c955c2936dcc80f546d05aacdb14
2020/03/18 12:55:15 pushed blob: sha256:31edd741225a32a24bb0537258544d8ac388a7966abda10028819bf514e1747e
2020/03/18 12:55:15 pushed blob: sha256:47edca1e960db990aa81c07f25b6f71fd36b8336d412989ec58da6c547f517f3
2020/03/18 12:55:15 pushed blob: sha256:ff29fe009c486d7c6adea36530e7d2f61374ceb078ba9ce7fc1d63f69e4b9700
2020/03/18 12:55:16 685249416972.dkr.ecr.ap-south-1.amazonaws.com/vicky-socs/test-python-jenkinsx:0.0.0-SNAPSHOT-PR-3-1: digest: sha256:2fde2f30c7f12a308a644d6fda92bd1102953245e524d4fbdc8179a0bf85ac3c size: 2385

Showing logs for build [32mvicky-socs-test-python-jenkinsx-f5llb-1[0m stage [32mfrom-build-pack[0m and container [32mstep-postbuild-post-build[0m
no CVE provider running in the current ** namespace so skip adding image to be analysed

Showing logs for build [32mvicky-socs-test-python-jenkinsx-f5llb-1[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-make-preview[0m
sed -i -e "s/version:.*/version: 0.0.0-SNAPSHOT-PR-3-1/" Chart.yaml
sed -i -e "s/version:.*/version: 0.0.0-SNAPSHOT-PR-3-1/" ../*/Chart.yaml
sed -i -e "s|repository:.*|repository: 685249416972.dkr.ecr.ap-south-1.amazonaws.com\/vicky-socs\/test-python-jenkinsx|" values.yaml
sed -i -e "s/tag:.*/tag: 0.0.0-SNAPSHOT-PR-3-1/" values.yaml
echo "  version: 0.0.0-SNAPSHOT-PR-3-1" >> requirements.yaml
** step helm build
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Adding missing Helm repo: storage.googleapis.com https://storage.googleapis.com/chartmuseum.jenkins-x.io
Successfully added Helm repository storage.googleapis.com.
Adding missing Helm repo: jenkins-x-chartmuseum http://jenkins-x-chartmuseum:8080
Successfully added Helm repository jenkins-x-chartmuseum.
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Adding missing Helm repo: chartmuseum.jenkins-x.io http://chartmuseum.jenkins-x.io
Successfully added Helm repository chartmuseum.jenkins-x.io.

Showing logs for build [32mvicky-socs-test-python-jenkinsx-f5llb-1[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-jx-preview[0m
Creating a preview
Found commit author match for: ******** with email address: 60379210+********@users.noreply.github.com
Created environment vicky-socs-test-python-jenkinsx-pr-3
Namespace **-vicky-socs-test-python-jenkinsx-pr-3 created 
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  config:
    domain: 3.7.28.134.nip.io
    exposer: Ingress
    http: "true"
preview:
  image:
    repository: 685249416972.dkr.ecr.ap-south-1.amazonaws.com/vicky-socs/test-python-jenkinsx
    tag: 0.0.0-SNAPSHOT-PR-3-1

Updating PipelineActivities vicky-socs-test-python-jenkinsx-pr-3-1 which has status Running
Preview application is now available at: http://test-python-jenkinsx.**-vicky-socs-test-python-jenkinsx-pr-3.3.7.28.134.nip.io
